function names = dart_diag_names()
%DART_DIAG_NAMES Names of the entries of the controller diagnostic vector.
names = {'N', 'T_scan', 'risk', 'ttc', 'min_dc', 'n_tracks', 'emergency', ...
    'trigger', 'cbf_active', 'cbf_slack', 'mpc_time', 'mpc_iter', 'mpc_status', ...
    'cbf_dev', 'tau_hat', 'latency', 'n_det', 'h_min', 'speed', 'mpc_rows', ...
    'near_id', 'near_cx', 'near_cy', 'near_cz', 'mpc_solved', 'n_gate_rej'};
end
